name: MiniMOTD
version: ${project.version}
main: xyz.jpenilla.minimotd.spigot.MiniMOTD
load: STARTUP
softdepend: [Prisma]
authors: [jmp]
description: Set the server MOTD using MiniMessage!
website: https://www.spigotmc.org/resources/minimotd.81254/
commands:
  minimotd:
    description: MiniMOTD command
    permission-message:
    usage: /minimotd help